<?php

namespace Gt\ItBundle\Entity;

/**
 * EmprunteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmprunteRepository extends \Doctrine\ORM\EntityRepository
{

}
